### ISSUE TITLE
Migrate azure func to create index from dev to prod (and activate)

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/ssc-assistant#133]
Azure func currently lives in our `dev` we need to migrate it to `prod-pilot`. And then we need to automate the usage of it by the ssc-assistant

## tasks

- [x] remove the dev azure functions from running,
- [x] create/move the `terraform` configuration for `dev` to `prod-pilot`.
- [x] create a new functions that update the current index on the chatbot. (index rename?)

**Comment by GuillaumeTurcotte** [comment]
https://learn.microsoft.com/en-us/azure/search/search-what-is-data-import

this could be used to cut down on cost and remove the azure function that builds the index in dev, and instead just copy the prod index to dev from time to time.

**Comment by GuillaumeTurcotte** [comment]
TF states also now stored remotely.

**Comment by GuillaumeTurcotte** [comment]
ran indexer on prod, seems to work with manual trigger, will run auto this weekend. 

Just need to create a function or trigger somewhere that restart the chatbot or updates the index named `latest` or add code functionality that uses the latest index.

**Comment by kyleaitken** [comment]
This might also work: https://learn.microsoft.com/en-us/azure/search/search-how-to-alias?tabs=rest

We can create an alias for an index called "latest" and then just point that alias to the most recent index after it's finished being created. Perhaps in another timer triggered function that also checks that the index was successfully populated after the build-index function is complete before switching the alias

**Comment by GuillaumeTurcotte** [comment]
Function not running because of access issues: 

> 2024-07-04T12:02:40Z   [Information]   HTTP Request: POST https://scsc-cio-ect-openai-oai.openai.azure.com//openai/deployments/text-
> embedding-ada-002/embeddings?api-version=2023-07-01-preview "HTTP/1.1 401 Unauthorized"
> 2024-07-04T12:02:40Z   [Error]   4e51e74ff425485ca66e816cdfab1953: Function 'build_search_index (Orchestrator)' failed with an error. Reason: Message: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}, StackTrace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. RuntimeStatus: Failed. HubName: indexmgmt. AppName: index-mgmt. SlotName: Production. ExtensionVersion: 2.13.2. SequenceNumber: 16. TaskEventId: -1
> 2024-07-04T12:02:40Z   [Error]   Executed 'Functions.build_search_index' (Failed, Id=e49dff13-2177-4758-84d3-aff377aaeb6b, Duration=37922ms)
> 2024-07-04T12:02:40Z   [Information]   4e51e74ff425485ca66e816cdfab1953: Orchestration 'build_search_index' awaited and scheduled 1 durable operation(s).
> 2024-07-04T12:02:40Z   [Information]   4e51e74ff425485ca66e816cdfab1953: Orchestration completed with a 'Failed' status and 228 bytes of output. Details: Message: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}, StackTrace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150
> 2024-07-04T12:02:42Z   [Information]   4e51e74ff425485ca66e816cdfab1953: Appended 4 new events to the history table in 0ms
> 2024-07-04T12:02:42Z   [Information]   4e51e74ff425485ca66e816cdfab1953: Updated Instances table and set the runtime status to 'Failed'
> 2024-07-04T12:02:42Z   [Information]   4e51e74ff425485ca66e816cdfab1953: Deleting [TaskCompleted#0] message from indexmgmt-control-00

**Comment by GuillaumeTurcotte** [comment]
Index seems to build now but it's missing the vector portion.

**Comment by kyleaitken** [comment]
From the llamaIndex example here: https://docs.llamaindex.ai/en/stable/examples/vector_stores/AzureAISearchIndexDemo/

These were the only things I could see that were different: 

![Image](https://github.com/dto-btn/ssc-assistant/assets/82782929/430397c6-7a18-43d7-b961-f049bd9c90cc)

I saw you added the doc id and algorithm type, so maybe it's the missing metadata field 'type' tripping it up?

**Comment by GuillaumeTurcotte** [comment]
https://github.com/dto-btn/ssc-assistant/commit/9791b5a0ef7ca97201aea4bd72bf82e7ceb0b090#diff-555e919d872cc197344f6bc16e93821da0b529f90950c125869652f4b0f2b781.

I noticed it was there back then aswell however the meteadata has drifted as you point out. Maybe was not an issue back then but might be an issue now, I will try to rerun with the proper mapping and see.

**Comment by GuillaumeTurcotte** [comment]
done and all is working beside the alias, which seems to hang the function, will create a separate issue to fix that.
