### ISSUE TITLE
Improve logging or store questions in db for audit purposes

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/ssc-assistant#4]
Current logging is left to be desired. We need to improve logging to enhance our capability of auditing the questions asked in order to imrpove the chatbot/myssc+ content.

## Tasks

- [ ] create TF template for a database that will receive the data.
- [ ] log every request made to the server (payload sent, etc) to the db
- [ ] log every response made by the server  to the db
- [ ] have a new endpoint in the backend that can receive feedback
- [ ] feedback will be stored in the same database as the chat logs audit section
- [ ] feedback endpoint must be secured like other endpoints and require a specific key to be used.
- [ ] feedback endpoint should receive at least 3 things: current conversation chain, along with "highlighted" message (the message the feedback was clicked on), the feedback (good or bad) and the message that is optional.

## BONUS

- [ ] investigate if we can control headers we receive to the app from the reverseproxy/idp authentication flow (user id/or other information for stats purpose (unique users, etc)

**Comment by GuillaumeTurcotte** [comment]
In relation to https://github.com/dto-btn/ssc-assistant/issues/57
