### ISSUE TITLE
Improve create-index azure function (durable, logging, params)

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/ssc-assistant#5]
There are a few tweaks that needs to be done to the new function that index to a Azure Search Service.

## Tasks

- [ ] make function durable
- [ ] improve logging?
- [ ] make the directory it reads from parametrizable
- [ ] fix the terraform template code to inject the proper variables (see `README.md` doc on `.env`)
- [ ] add terraform Azure Automation task to trigger this function (see example in `chatbot-infra` for example on Azure Automation task). Could also look at other alternatives.
